// Generated by CoffeeScript 1.3.3
(function() {
  var logEntry;

  logEntry = (function() {

    function logEntry(data) {
      var now;
      console.log(data);
      this.callsign = data.srccallsign;
      this.latitude = data.latitude;
      this.longitude = data.longitude;
      this.altitude = data.altitude;
      this.timestamp = data.timestamp;
      this.speed = data.speed;
      this.comment = data.comment;
      if (data.timestamp === void 0) {
        now = new Date(new Date().toUTCString());
        this.timestamp = Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate(), now.getUTCHours(), now.getUTCMinutes(), now.getUTCSeconds(), now.getUTCMilliseconds());
      }
      console.log("callsign %s", this.callsign);
      console.log("latitude %s", this.latitude);
      console.log("longitude %s", this.longitude);
      console.log("altitude %s", this.altitude);
      console.log("timestamp %s", this.timestamp);
      console.log("speed %s", this.speed);
      console.log("comment %s", this.comment);
    }

    logEntry.prototype.postReceive = function(collection, io) {
      if (this.isValid()) {
        console.log("Inserting");
        collection.insert(this);
        console.log("Broadcasting");
        return io.emit('update', [this]);
      }
    };

    logEntry.prototype.isValid = function() {
      return (this.callsign != null) && (this.latitude != null) && (this.longitude != null) && (this.timestamp != null);
    };

    logEntry.prototype.toString = function() {
      return JSON.stringify(this);
    };

    return logEntry;

  })();

  module.exports = logEntry;

}).call(this);
